language: node_js
node_js:
  - node
scripts:
  - npm run build
  - npm run lint
  - npm run test-with-coverage
after_success:
  - nyc report --reporter=text-lcov > coverage.lcov
  - codecov
git:
  depth: false
cache:
  directories:
    - node_modules
